--- #YAML:1.0
name:                CatalystX-CRUD-View-Excel
version:             0.05
abstract:            view CRUD search/list results in Excel format
license:             ~
author:              
    - Peter Karman <karman at cpan dot org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Catalyst::View::Excel::Template::Plus: 0
    CatalystX::CRUD:               0.27
    Path::Class:                   0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
