--- #YAML:1.0
name:               CatalystX-CRUD-View-Excel
version:            0.07
abstract:           view CRUD search/list results in Excel format
author:
    - Peter Karman <karman at cpan dot org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst::View::Excel::Template::Plus:  0
    CatalystX::CRUD:      0.27
    Path::Class:          0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
